job-info / flux-jobs: Support listing nodelist
flux-framework/flux-core pull request #3332
Opened 2020-11-12 02:24 UTC by chu11

Per #3313 and #3323, convert `job-info` to use `librlist`, then add `nodelist` as a listable attribute in `job-info`.  Added fix for #3322 in here as well.

Most of the changes in this PR aren't earth shattering, pretty basic.  But two things to note for possible discussion:

- I changed the default output of `flux-jobs` to list `NODELIST` instead of `RANKS`, b/c I figure that's what most users probably want by default.  I doubt this change is controversial.  Unless someone thinks we should list both `RANKS` and `NODELIST`?

- I think the `NNODES` attribute is a bit ambiguous now w/ `NODELIST` output available.  We could have a situation where multiple brokers exist on a node, so the number of ranks might be > 1, but the number of nodes is a different number.  Here's a simple example:

```
>flux jobs -A
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
    ƒ9E6hswD achu     hostname   CD      4      2   0.099s catalyst[159,159]
    ƒ7fzjXZh achu     hostname   CD      4      4   0.136s catalyst[159,159,159,159]
```

I was about change `NNODES` to be `NRANKS`, then implement a new field `NNODES` that is the actual number of nodes the job ran on.  But I noticed that `nnodes` is used in `librlist` and it has meaning there as.

Perhaps `NNODES` is fine it doesn't have to be changed.  Maybe all that needs to be done is `NNODES` needs to be clarified in the documentation to be "resource nodes", not "physical nodes"?

Or perhaps `NNODES` needs to be changed globally?

2020-11-12 03:13 UTC, grondo commented
> Perhaps NNODES is fine it doesn't have to be changed. Maybe all that needs to be done is NNODES needs to be clarified in the documentation to be "resource nodes", not "physical nodes"?
>
> Or perhaps NNODES needs to be changed globally?

For now, ranks (or better: execution targets) and "nodes" are synonymous. I think we should worry about this problem later (e.g. Rv2). If someone is running multiple brokers per physical node then it is for testing purposes and/or experimentation, and each rank should be treated as a "node" or else we won't be able to the situation as  a valid "multi node" test scenario.


> I think the NNODES attribute is a bit ambiguous now w/ NODELIST output available. We could have a situation where multiple brokers exist on a node, so the number of ranks might be > 1, but the number of nodes is a different number. Here's a simple example:

Hm, this statement confused me so maybe I don't understand the problem correctly. In your example NNODES matched the count of hosts in the NODELIST (only the hostnames are repeated). This probably won't be an issue in practice.

> I changed the default output of flux-jobs to list NODELIST instead of RANKS, b/c I figure that's what most users probably want by default. I doubt this change is controversial. Unless someone thinks we should list both RANKS and NODELIST?

I don't think we need RANKS and NODELIST -- I kind of like RANKS instead of NODELIST for brevity, and also as a better abstraction for hierarchical jobs, but I think you're right NODELIST is the right default.

This is actually a pretty big step forward in usability I think.

2020-11-12 05:10 UTC, chu11 commented
> Hm, this statement confused me so maybe I don't understand the problem correctly. In your example NNODES matched the count of hosts in the NODELIST (only the hostnames are repeated). This probably won't be an issue in practice.

For me, I looked at a nodelist of `catalyst[159,159]` and thought nnodes should be 1, not 2.

> I think we should worry about this problem later (e.g. Rv2). 

sounds good to me

2020-11-12 05:15 UTC, chu11 commented
re-pushed fixing a chain lint issue

2020-11-12 15:18 UTC, grondo commented
> For me, I looked at a nodelist of catalyst[159,159] and thought nnodes should be 1, not 2.

No, because each rank is pretending to be a whole "node", either duplicating resources or splitting them in some way, this should be thought of (for now) as two nodes with the same hostname.

2020-11-14 16:50 UTC, grondo requested changes
LGTM too! This is a nice little enhancement! It is nice to see hostnames rather than ranks by default in `flux jobs` output:

```
ƒ(s=8,builddir) grondo@fluke3:~/git/flux-core.git$ flux jobs -a
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
    ƒDmUrHgK grondo   sleep      CD      2      2   10.06s fluke[3,64]
    ƒDhhS7yH grondo   sleep      CD      2      2   10.06s fluke[69-70]
    ƒDdv1xGF grondo   sleep      CD      2      2   10.06s fluke[67-68]
    ƒDa8bnZD grondo   sleep      CD      2      2   10.05s fluke[65-66]
    ƒDWGjf19 grondo   sleep      CD      2      2   10.06s fluke[3,64]
```

Just one very minor change requested in the inline comments.

2020-11-14 16:50 UTC, grondo commented on src/modules/job-info/job_state.c
> +        flux_log_error (ctx->h, "rlist_from_json: %s", strerror (errno));
`rlist_from_json()` takes a `json_error_t` as well, so this should be:
```c
    if (!(rl = rlist_from_json (job->R, &error))) {
        flux_log_error (ctx->h, "rlist_from_json: %s", error.text);
        goto nonfatal_error;
    }

```

2020-11-14 19:24 UTC, chu11 commented
rebased & re-pushed with @grondo's comment fix above

2020-11-14 20:45 UTC, grondo approved these changes
Thanks! LGTM!

2020-11-15 17:08 UTC, grondo commented
Ok to set MWP?

2020-11-15 20:13 UTC, chu11 commented
thanks, setting MWP

2020-11-15 20:14 UTC, merged