job-manager: do not checkpoint on every queue state change
flux-framework/flux-core pull request #4856
Opened 2023-01-05 16:15 UTC by chu11

Per #4804, the number of checkpoints to the KVS seems a bit excessive, as it occurs on every change.

Instead, do it only when the user asks to via a `sync` flag.  So that users can say "hey preserve this specific change just in case", as well as to help with testing.

I made one additional change that I think is important, when checkpointing in the `job-manager`, make sure that the FLUX_KVS_SYNC flag is set, to ensure the data is on the backing store as well.

2023-01-09 17:36 UTC, garlick requested changes
As noted inline, I think the KVS_SYNC flag is inappropriate, and the user-facing option is probably not the right way to go.   However, maybe the change suggested in #4856 is going too far in the opposite direction?

If we left the KVS commit of queue state changes as is, then at least `kvs.checkpoint-period` would make sure the backing store is kept reasonably current in the event of a crash.  Thoughts?

2023-01-09 17:36 UTC, garlick commented on src/modules/job-manager/restart.c
> +        || !(f = flux_kvs_commit (ctx->h, NULL, FLUX_KVS_SYNC, txn))
Again - high cost operation, and we already have `kvs.checkpoint-period` periodically saving the KVS root.

2023-01-09 17:36 UTC, garlick commented on src/cmd/flux-queue.c
> +    },
As noted previously I think this option is not something an admin needs/wants.

2023-01-09 18:29 UTC, chu11 commented on src/modules/job-manager/queue.c
> +    }
Yeah, I basically went down this path solely to keep some current tests working (they check `checkpoint.job-manager` directly after a `flux queue enable/disable/start/stop`.  Will re-do and just re-work the tests instead!

2023-01-11 05:33 UTC, chu11 commented
re-pushed, going with an alternate approach.  Simply do not checkpoint on every queue state change, only checkpoint when the `job-manager` module is unloaded.

Had to update some tests as a result.

2023-01-19 17:55 UTC, garlick approved these changes
LGTM!

2023-01-20 18:52 UTC, garlick commented
Any reason not to set MWP on this?

2023-01-20 19:14 UTC, chu11 commented
nope, was just waiting for your approval :-)

2023-01-20 19:52 UTC, merged